version: "3.7"

services:
  api:
    depends_on:
      - db
    ports:
      - "127.0.0.1:5000:5000"
    build:
      dockerfile: ./api/Dockerfile
      context: .
    volumes:
      - ./api:/home/user/api
    environment:
      - DB_STRING=postgresql://postgres:test@db:5442/postgres

  db:
    image: postgres:14.5
    ports:
      - "127.0.0.1:5442:5442"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=test

volumes:
  postgres-data:
